kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-dynamic-roboshop-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap # efs-accessPoint
  fileSystemId: fs-073a72a9c3f40e653
  directoryPerms: "700"
  gidRangeStart: "1000" # optional
  gidRangeEnd: "2000" # optional
  basePath: "/roboshop" # I am creating storage for my roboshop project. This will be the accesspoint.
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-dynamic-pvc
spec:
  storageClassName: "efs-dynamic-roboshop-sc"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels: # these labels belong to deployment
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels: # these labels should match with pod
      app: nginx
      project: roboshop
      component: frontend
  template: # this is the pod definition
    metadata:
      labels:
        app: nginx
        project: roboshop
        component: frontend
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-volume
              mountPath: /usr/var/share/nginx/html
      volumes:
        - name: nginx-volume
          persistentVolumeClaim: # this is the pvc
            claimName: efs-dynamic-pvc
