apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: node-list-clusterrole
rules:
  - apiGroups: ["v1", "apps/v1", ""]
    resources: [
        "secrets",
        "nodes",
        "namespaces",
        "persistentvolumes",
        "deployments",
      ] # here i am providing some extra access.
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tony-node-lister-clusterrolebinding
subjects:
  - kind: User
    name: tony # Name is case sensitive
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: node-list-clusterrole
  apiGroup: rbac.authorization.k8s.io
