FROM almalinux:8    
# RUN instruction is used to install packages or congifure the settings inside your base image.
# The RUN instruction will execute any commands to create a new layer on top of the current image
RUN yum install nginx -y 