apiVersion: v1
kind: Pod
metadata:
  name: config-map-env-prod
spec:
  containers:
    - name: app-container
      image: nginx
      env:
        - name: DB_user
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: username
        - name: DB_pass
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: password
