FROM centos:8
# FROM is the instruction used to select the base image for subsequent instructions.
# It can appear many times in a single docker file.
# Dockerfile must start with a FROM instruction.  