apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: roboshop
  labels: # these labels belong to the deployment
    app: user
    tier: app
    project: roboshop
spec:
  replicas: 1
  selector:
    matchLabels: # these labels should match with pod lables.
      app: user
      tier: app
      project: roboshop
  template:
    metadata:
      name: user
      labels:
        app: user
        tier: app
        project: roboshop
    spec:
      containers:
        - image: bhargav863/user:1.0.0
          name: user
          envFrom:
            - configMapRef:
                name: user-config

---
apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: roboshop
spec:
  selector:
    app: user
    tier: app
    project: roboshop
  ports:
    - name: user-port
      port: 8080 # this belongs to the service
      protocol: TCP
      targetPort: 8080 # this port belongs to the container
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-config
  namespace: roboshop
data:
  REDIS_HOST: "redis" # keep true in double quotes
  CATALOGUE_HOST: "catalogue"
  CATALOGUE_PORT: "8080"
