apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: roboshop
  labels: # these labels belong to the deployment
    app: rabbitmq
    tier: db
    project: roboshop
spec:
  replicas: 1
  selector:
    matchLabels: # these labels should match with pod lables.
      app: rabbitmq
      tier: db
      project: roboshop
  template:
    metadata:
      name: rabbitmq
      labels:
        app: rabbitmq
        tier: db
        project: roboshop
    spec:
      containers:
        - image: rabbitmq
          name: rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: roboshop
spec:
  selector:
    app: rabbitmq
    tier: db
    project: roboshop
  ports:
    - name: rabbitmq-port
      port: 5672 # this belongs to the service
      protocol: TCP
      targetPort: 5672 # this port belongs to the container
