- name: Loops Example
  hosts: all
  tasks:
    - name: print the names
      ansible.builtin.debug:
         msg: Hello {{ item }}
      loop:
       - ansible
       - jenkins
       - terraform
       - cloud