- name: setup the mongodb repo
  ansible.builtin.import_role:
     name: common
     tasks_from: mongo.yaml
- name: install the mongodb
  ansible.builtin.apt:
    name: mongodb-org
    state: present
    update_cache: yes
    
- name: Replace bind address in configuration file
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '^(.*bindIP:\s*)127\.0\.0\.0'
    replace: '\1 0.0.0.0'

- name: restart the mongod service
  ansible.builtin.service:
    name: mongod
    state: restarted
      