- name: Variables at task level
  hosts: localhost
  vars:
    - fav_color: black
      fav_food: Biryani
  tasks:
    - name: inherit the values from play
      ansible.builting.debug:
         msg: |
             {{ fav_color }} is my favourite colour
             {{ fav_food }} is my favourite food.