- name: Variables from files
  hosts: localhost
  vars_files:
    - variablefile.yml
  tasks: 
    - name: print all the port numbers and users. variables from list
      ansible.builtin.debug:
        msg: |
          All the ports are {{ port_nums }}
          All the users are {{ users }}
    - name: print particular port number and user using index
      ansible.builtin.debug:
        msg: |
          Third port is {{ port_nums[2] }} 
          Third user in the list is {{ users[2] }}
# indexing will start from 0, port_num[0],port_num[1] like that
    - name: print the group and shell for the user bob.
      ansible.builtin.debug:
        msg: The group of the user {{ user_vars['bob']['username'] }} is {{ user_vars['bob']['group'] }} and the shell is {{ user_vars['bob']['shell'] }}
# this is one way of accessing the values from the dictionary
    - name: print the group and shell for user lisa
      ansible.buitlin.debug:
         msg: The group of the user {{ user_vars.lisa.username }} is {{ user_vars.lisa.group }} and the shell is {{ user_vars.lisa.shell }}
# This is another way of accessing elements from the dictionary
          
      