FROM almalinux:8 
ENV Name=Bhargav \
    Company=Accenture \
    Level=11 

# ENV instruction is used to set the Environment variables for our base image.
# The ENV instruction allows for multiple <key>=<value> ... variables to be set at one time.
# The environment variables set using ENV will persist when a container is run from the resulting image.

# docker run <Image_id> ENV