# register is used to stored the output of a command
- name: register playbook
  hosts: all
  become: true
  tasks:
    - name: check when the server is rebooted.
      ansible.builtin.command: uptime 
      register: server_uptime
    - name: print the uptime of the server
      ansible.builtin.debug:
        msg: {{ server_uptime }}