apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-pod
  namespace: roboshop
  labels: # These labels are deployment labels, every k8 resource should have lables.
    environment: dev
    app: frontend
spec:
  replicas: {{ .Values.deployment.replicaCount }} # specifies the number of pods to be created
  selector:
    matchLabels: # these labels should match pod lables.
      environment: dev
      tier: frontend
      app: nginx
  template: # template nothing but the pod definiton
    metadata:
      labels: # these are the pod labels.
        environment: dev
        tier: frontend
        app: nginx
    spec:
      containers:
        - image: "nginx:{{ .Values.deployment.ImageVersion }}"
          name: sample-nginx
          ports:
            - containerPort: 80

