apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  selector:
    environment: dev
    app: frontend
  ports:
    - name: name-of-the-service-port
      protocol: "TCP"
      port: 80 # This port belongs to the service
      targetPort: 80 # This port belongs to the container
