apiVersion: v1
kind: Pod
metadata:
  name: sample-pod
  labels:
    environment: dev
    app: frontend
spec:
  containers:
    - image: nginx
      name: sample-nginx
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  selector:
    environment: dev
    app: frontend
  ports:
    - name: name-of-the-service-port
      protocol: "TCP"
      port: 80 # This port belongs to the service
      targetPort: 80 # This port belongs to the container
