apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: roboshop
  labels: # these labels belong to the deployment
    app: redis
    tier: db
    project: roboshop
spec:
  replicas: 1
  selector:
    matchLabels: # these labels should match with pod lables.
      app: redis
      tier: db
      project: roboshop
  template:
    metadata:
      name: redis
      labels:
        app: redis
        tier: db
        project: roboshop
    spec:
      containers:
        - image: redis
          name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: roboshop
spec:
  selector:
    app: redis
    tier: db
    project: roboshop
  ports:
    - name: redis-port
      port: 6379 # this belongs to the service
      protocol: TCP
      targetPort: 6379 # this port belongs to the container
