FROM almalinux:8
RUN echo "Hello World"
RUN useradd Bhargav
USER Bhargav
# From here everything will be run using the Bhargav user.
# Login to the container once you created, you can see the user as Bhargav.