- name: Install nginx
  ansible.builtin.apt:
      name: nginx
      state: present
- name: Start and enable nginx
  ansible.builtin.service:
      name: nginx
      state: started
      enabled: true
- name: remove the default nginx files
  ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent
- name: Add the html directory
  ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory
- name: Download the web artifacts
  ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/web.zip
      dest: /tmp/web.zip
- name: Extract the content
  ansible.builtin.unarchive:
      src: /tmp/web.zip
      dest: /usr/share/nginx/html/
      remote_src: yes
- name: copy the roboshop.conf files
  ansible.builtin.template:
    src: roboshop.conf.j2
    dest: /etc/nginx/sites-available/default
  notify:
    - restart the nginx